// generated by @ng-toolkit/serverless
'use strict';

const functions = require('firebase-functions');
const admin = require("firebase-admin");
const nodemailer = require('nodemailer');
admin.initializeApp(functions.config().firebase);

// const gmailEmail = functions.config().gmail.email;
// const gmailPassword = functions.config().gmail.password;
// SMTP_PORT=587
// SMTP_AUTH_USER=dotafreelancer@gmail.com
// SMTP_AUTH_PASSWORD=XXxx11@@
const mailTransport = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'dotafreelancer@gmail.com',
    pass: 'XXxx11@@',
  }
});


const sendNotification = functions.firestore
  .document('/contact/{value}').onCreate((snap, context) => {
    const data = snap.data();
    // let email = data.email;;
    // let name = data.name;
    // if (email && name) {
    //   sendEmail('pirates582@gmail.com', 'Haha');
    // }
    sendEmail(data);

   
  });

const APP_NAME = 'Cloud Storage for Firebase quickstart';

const sendWelcomeEmail = functions.auth.user().onCreate((user) => {
  // [END onCreateTrigger]
  // [START eventAttributes]
  const email = user.email; // The email of the user.
  const displayName = user.displayName; // The display name of the user.
  // [END eventAttributes]

  return sendEmail(data);
});

function sendEmail(data) {
  const mailOptions = {
    from: 'dotafreelancer@gmail.com',
    to: 'pirates582@gmail.com',
  };

  // The user subscribed to the newsletter.
  mailOptions.subject = `Thông tin khách hàng ${data.email}`;
  mailOptions.text = `Thông tin khách hàng: ${data.name}, Email: ${data.email}, Số điện thoại: ${data.phone}, Điểm khơi hành: ${data.arrival}, Điểm đến: ${data.destination}, Thông điệp: ${data.message}`;
  return mailTransport.sendMail(mailOptions).then(() => {
    return console.log('New welcome email sent to:', 'pirates582@gmail.com');
  });
}

module.exports = {
  sendNotification
}
